### ISSUE TITLE
ナウイ開発したいよね

### ISSUE THREAD

**Issue by hulk510** [4m-mazi/mmmm#4]
github action? ci/cdやってみたいな。
かっこよくイキっていこうぜエンジニアなら。

**Comment by ikasoba** [comment]
これとこれを組み合わせたらできそうかも？
- https://github.com/cloudflare/pages-action
- https://github.com/denoland/setup-deno

**Comment by hulk510** [comment]
今cloudflareのアプリインストールして自動でデプロイしている気がするんやけど、これとはまた違うって感じなんかな？
![スクリーンショット 2023-07-31 2 50 06](https://github.com/4m-mazi/mmmm/assets/33943897/3f225e8b-4877-4d38-8eed-6e53597def28)

**Comment by ikasoba** [comment]
github actions使ってpagesにデプロイするようにするとやれることの幅が増えるけど、自動でデプロイ出来てるなら使わなくて大丈夫かも
別の言語とかも混ざってきたら使ったほうが良さそうかな(wasmとかを使わない限りはたぶんない)

**Comment by hulk510** [comment]
なるほどなるほど！
ありがとう😊
